### ISSUE TITLE
Audit is unable is not reporting missing models / Columns under models from schema

### ISSUE THREAD

**Issue by SudhirNune** [bitpicky/dbt-sugar#210]
If a Model is not documented or Model is available but few columns are missing then the Audit is not reporting these as issue and providing a audit % as 100%.

**Comment by bastienboutonnet** [comment]
Hi @SudhirNune and thank you for trying out the tool really!

So I know exactly what the issue here is. It's not really a bug but also not really a feature.

The reason why this behaviour is happening is that, during the audit task, we **rely exclusively on the model descriptor files**. We don't check that your model exists on the db nor do we check to see if a model exists as a file (the latter one I have to double check). But yes the short answer is if columns don't appear in the descriptor or models don't appear there they don't bubble up in the audit output.

Now, while it's less of a problem in the model-specific audit task, it's really quite terrible at the dbt project I agree.

There are a few things we could try here are some:
1. we could offer to "initialise" all your models and make place holder schema.yml with all your columns and a placeholder uncodumented string. Then you could run your audit and have it show up.
2. we could the approach I just mentioned "silently" before running the audit (just internally)
3. we could also just make sure that the "initialise" (with impact on files --so not silent) is always ran **before** we do the audit so that we don't require the user to think about initialising.

I'm curious what kind of alternative you'd most like as a user of the tool? I'm tempted to go for the third option, with potentially a config flag that could make it "silent" if I wanted to. I think 1. is a sad option as it requires user to think about running two things but it's the least surprising (meaning all of a sudden you're not running the risk of potentially committing large diffs because very few of your models were described.

I'm really curious what your opinions are on this.

Most likely we'll ship this in the beta of the next feature release and document the caveat for the current version as it will require writing quite a bit of new code and that brings more risk for bugs with the current set of features.

If you want to help with building this I'd be happy to support you through it if not I'll most likely give it a shot over the weekend.

**Comment by SudhirNune** [comment]
@bastienboutonnet - I would like to propose:

When the user runs Audit
> a. list the models from the "models" folder and sub folder and list them
> b. use these models and retrieve the Details from DB (Column Names)
> c. Compare them with the schema.yml documentation and list the differences & Score it. it should be nice to have a score for Model Desc(1) + Column Desc (9) which will give the Complete Model score out of 10

the above process can be optional by --ignore-db-check switch in case the user wants to ignore comparison with DB Table.

**Comment by bastienboutonnet** [comment]
Yeah I think pinging the db isn't an issue at all and I like what you say about the output of the task. I'll work on this over the weekend I think. There are a few parts to build that aren't there but should be ok. 

I'll let you know when there's an alpha of v0.1.0 you can play with if you like.

**Comment by bastienboutonnet** [comment]
Hi again @SudhirNune I'm gonna take a bit more time with this. I kind of came back on my decision after chatting with @virvirlopez .

We don't want the audit task to always ping the db. Rather we will offer the following:
- a task to "bootstrap" the model which will add documentation entry placeholders for all models in the dbt project. This task will ping the db (just like the documentation task)
- the audit task will remain as is (meaning that it will solely rely on already generated entries) **however** we will add a CLI flag which will read something like `--check-all-models`. When passed, this flag will essentially do what you propose and check for all models in the db.

This allows for a bit more flexibility and makes sure that if some users have large dbt models the audit task doesn't have to take that long. We prefer to leave it to the user whether they want to bootstrap their entire project or not and whether they want a thorough or light version of the audit task.

I'll be working on this in the coming days and let you know here when we have something for you to test if you want.

Hope this sounds ok to you.
