### ISSUE TITLE
What subtasks would make sense in the `DocumentTask`?

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#24]
Just putting this out there to get some dicussion @virvirlopez 

What do we think we want to have in the first (and following implementations). I could see all the following sub tasks:
- add model description from user input
- add descriptions to empty columns (or modify existing ones) from user input
- allow for existing columns with definitions to propagate onto new ones (I have a feeling this should be optional and down to user choice. Maybe for some teams they do not want to homogeneise column descriptions).
- add tests (and have them ran in the db)
- add tags? (I think the prio on this might be quite low I think it might be a pretty uncommonly used feature but maybe something we could ask about).
- homogenise definitions (this is a bit more long term but I think I definitely want to find a way to make this happen).

What are your thoughts and maybe what do you think about prioritisation on this?

**Comment by bastienboutonnet** [comment]
For the human input regarding which columns to document I would think that we can use this question type: https://questionary.readthedocs.io/en/stable/pages/types.html#type-checkbox

We would maybe want to render the documentation. It would look something like this:

```
? Select any number of columns you would like to document
o column_a, desc: this is the description.
o column_b, desc: no description for this column
```

When we add tests and maybe other details maybe this will get crowded and we can see about rendering a sumary table or so.

If we have this the flow would go:
- user selects any number of columns
- this gets passed to the documentation task
- documentation task iterates and asks for definitions using the following question type from `questionary`: https://questionary.readthedocs.io/en/stable/pages/types.html#text

**Comment by jflairie** [comment]
> allow for existing columns with definitions to propagate onto new ones (I have a feeling this should be optional and down to user choice. Maybe for some teams they do not want to homogeneise column descriptions).

I agree this should be optional, likely something you can configure globally.

**Comment by jflairie** [comment]
Other idea: add features around documentation coverage
- how many models have a description?
- how many columns are documented? tested?
- what are the most "popular" columns which are not documented? tested? (this is to prioritise the output of the previous bullet point)

**Comment by bastienboutonnet** [comment]
@virvirlopez I'm writing some of your great ideas from my call with you earlier. I think those are killer features!

- Smart Tags: We should offer a way for people to express and store rules to do some automatic tagging. For example users could say: "when `email` is in the column description tag as `PII`" and stuff like this.
- Smart Tests: if a primary key is given in the `{{config()}}` block how about we automatically place or suggest uniqueness and not null tests to be added on that column?

**Comment by bastienboutonnet** [comment]
@jflairie Thanks for chiming in! I really like your ideas around having a documentation and test coverage report.

I think it would be a different "task" or an option within the documentation flow but yeah totally one to place on the roadmap at some point.

**Comment by bastienboutonnet** [comment]
One of our community members posted a link to two of Emily's (Netlify) articles on column namings as contracts. I think leveraging such a naming convention could allow us to guess or propose tests to enforce in a smart way.

References here: 
- https://emilyriederer.netlify.app/post/column-name-contracts/
- https://emilyriederer.netlify.app/post/convo-dbt/

I'll make an issue specifically focused on these as this ticket is getting a bit general now and I'd like to track the progress of tags and tests ideas in a more transparent way.

**Comment by noel** [comment]
When I think about something like this first I think of a helper process that accelerates the existing process without changing the UX. 

So, without creating a UI for the user, I am just thinking of a process that first creates the model.yml (which btw I create one per model vs one for all models as is typically shown in dbt docs).  This is similar to dbt-codegen.

Next, I like the idea of metrics.  I would want to know of all the "final" tables that I have how many are missing a description.  I can determine "final" based on folder structure.

Then of all the columns in the final models, how many have descriptions.

Regarding inheritance, if it is possible to see that a column is in a child model and the parent model had the description for that column named exactly the same way, then this parent column description would be added to the generated yml as a suggested starting point.

Regarding propagating tags, I am thinking of propagating specific meta: attributes given that the child model has a field with the same name.  I would also add this to the model itself and all child models. e.g. 
```columns:
  name: first_name
  description: First name of the patient
  meta:
     classification: pii
```
The idea is that if a table has a pii column, then the table is also marked as pii.  Also, if a table is derived from a pii table, then it too is classified as pii.  

Since these are just helpers, the user is still able to modify the resulting yml, we are just providing some hints to them to speed up their documentation work and hopefully avoid careless mistakes.  We could also add hints to the PR for a reviewer to validate certain things.
