### ISSUE TITLE
Redshift connector not working properly

### ISSUE THREAD

**Issue by ldbrandi** [bitpicky/dbt-sugar#262]
Hello, I've just started testing the alpha version `0.1.0-a.3` with Redshift, but I went through some errors:

When running `dbt-sugar bootstrap` it returns the **NotImplemented** error:
```
NotImplementedError:
Connector 'redshift' is not implemented.
```

Also, when running `dbt-sugar doc`, there are connection errors:
```dbt-sugar 8 <module>
"/Users/l.brandi/.local/share/virtualenvs/dbt-ula5LEz1/bin/dbt-sugar", line 8
  import sys
  from dbt_sugar.core.main import main
  if __name__ == '__main__':
      sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
>     sys.exit(main())
  
  
  
  

dialect.py 747 _get_all_column_info
"/Users/l.brandi/.local/share/virtualenvs/dbt-ula5LEz1/lib/python3.9/site-packages/sqlalchemy_redshift/dialect.py", line 747
      return relations
  
  @reflection.cache
  def _get_all_column_info(self, connection, **kw):
      all_columns = defaultdict(list)
>     with connection.contextual_connect() as cc:
          result = cc.execute("""
          SELECT

self: <sqlalchemy_redshift.dialect.RedshiftDialect object at 0x104a0ea00>
connection: <sqlalchemy.engine.base.Connection object at 0x104d18be0>
kw: {'info_cache': {}}
all_columns: defaultdict(<class 'list'>, {})

AttributeError:
'Connection' object has no attribute 'contextual_connect'
```

Looking forward to testing it in more detail, let me know if you need more pieces of evidence.

**Comment by ldbrandi** [comment]
Oh, note sure if it is useful or not, but I installed using `pip` and I'm working with `pyenv` and `pipenv` environments.

**Comment by bastienboutonnet** [comment]
Thanks @ldbrandi for the report. 

Putting this doc as a reference: https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector

It looks like sqlalchemy prefers to use a newer version of inspect but I doubt that that's the choice.

I also found this issue: https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/214 it seems like there is work needed to be done on https://github.com/sqlalchemy-redshift/sqlalchemy-redshift

I think we may have to try downgrading sqlalchemy to below 1.4. This is not ideal though and maybe it means I should break down the package a bit so that we can allow users of not redshift to use different stuff.

I'll try and open a PR with a downgraded sqlalchemy now and you could have a go if you wanted.

**Comment by bastienboutonnet** [comment]
Ok I've published a new build on the **test** pypi. Since you're using pip could you create a new virtual env and install it with the following line (which will point to the test pypi --I don't want to release it to the world just yet if it's not gonna work)

`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ dbt-sugar==0.1.0a4`

The associated PR is here: https://github.com/bitpicky/dbt-sugar/pull/263

I've also added a fix for the bootstrap task (we ended up duplicating some code and this bit up in the ass. I'll correct this soon though)

So yeah let me know if both work for you now

🤞

**Comment by ldbrandi** [comment]
Hi Bastien! It's working!

I'll make other tests in other features as well but for the ones I've mentioned before, you can consider fixed :)
