### ISSUE TITLE
Add parameter to locate profiles.yml

### ISSUE THREAD

**Issue by diegodewilde** [bitpicky/dbt-sugar#273]
Currently, the default behaviour is to search for a `.dbt` folder in the home directory. 
It would be great to have it as a parameter in the `sugar_config.yml` so other locations can be used.

**Comment by bastienboutonnet** [comment]
Hi @diegodewilde thanks for trying the tool out <3.

Out of curiosity which version of dbt-sugar are you currently using?

I'm going to have to think about this particular usage because it is not really in line with how [dbt advises things to be ](https://docs.getdbt.com/dbt-cli/configure-your-profile#advanced-profile-configuration) and I'd like to be as close as possible to where we can expect those files to be.

That being said, there are a few ways in which you can override the default search. Which are exactly in line with how [dbt does it](https://docs.getdbt.com/dbt-cli/configure-your-profile#advanced-profile-configuration) being:
- using the runtime CLI argument --profiles-dir (supported since the very first version of dbt-sugar)
- using environment variable `DBT_PROFILES_DIR` (supported as of `v0.1.0-a.3`)

Do you buy that at all or you have a strong feeling about making this part of the `sugar_config.yml`?

**Comment by diegodewilde** [comment]
Hi @bastienboutonnet; it seems like a very nice tool to ignore. 

I'm currently using the `--profiles-dir` CLI argument and wasn't aware that this works with **dbt-sugar** as well!
Looks like I've found a solution for now! *cheers*

Please ignore my suggestion; I don't see any advantage to make it part of `sugar_config.yml` for now. 

Thanks for your quick response!

**Comment by bastienboutonnet** [comment]
> Hi @bastienboutonnet; it seems like a very nice tool to ignore. 
to ignore?

Glad you're on board with the decision. It is available but I haven't documented it on gitbook yet. I **think** doing `dbt-sugar doc --help` should have shown that it was available but you may not have though of that as a possibility.

I'll make an issue to update the docs because I'm sure you're not the only one with that use case in mind.

**Comment by diegodewilde** [comment]
> > Hi @bastienboutonnet; it seems like a very nice tool to ignore.
> 
> to ignore?
> 

Semantic issue; I thought of it like "it's too nice to ignore it" 🥇  

Great; thanks for the support; I'll use `dbt-sugar doc --help` from now on!
