### ISSUE TITLE
Export `dbt-sugar audit` into standard code coverage format

### ISSUE THREAD

**Issue by k-aranke** [bitpicky/dbt-sugar#351]
**Is your feature request related to a problem? Please describe.**
I want to export the code coverage from `dbt-sugar audit` into a standard format that code coverage tools like [codecov](https://about.codecov.io/) can consume.

**Describe the solution you'd like**
`dbt-sugar audit` writes a standard code coverage file that tools like [codecov](https://about.codecov.io/) can pick up.
Maybe this is hidden behind a flag and is not default behavior?

**Describe alternatives you've considered**
N/A

**Additional context**
I initially brought this up in Discord (#dbt-sugar-help) and was told to create an issue.

**Comment by bastienboutonnet** [comment]
That's a pretty decent idea @k-aranke ! I think I thought about doing it at some point but I didn't really feel like I wanted to dive into it at the time. Do you think you would be able to contribute to this feature?

These are apparently the formats which codecov will pick up: https://docs.codecov.com/docs/supported-report-formats

We'd have to make sure to serialise the data object that build the CLI coverage report in at least one of these formats. I'm not sure if this would be straightforward though. Do you have an idea already? How could I best support you?

**Comment by bastienboutonnet** [comment]
For codecov they allow a kind of custom json output: https://docs.codecov.com/docs/codecov-custom-coverage-format

Might be a good way to start. Otherwise we have to understand and map things to the XML formats? Unless you know well how those files are structured or we backward engineer from a pytest output.

**Comment by k-aranke** [comment]
Thanks for your support, @bastienboutonnet.

I was able to do some research on the topic over the weekend and realized what I **do not** want to build for this task:
1. A runner to run tests
2. A reporter to collect metrics on code coverage
3. An uploader to upload these metrics to a code coverage tool

Given these constraints, I think the best approach to move forward would be to plug into an existing code coverage tool so that people can use existing workflows.

After surveying the landscape, I think [`coverage.py`](https://coverage.readthedocs.io/en/6.0/index.html) is the best option since the DBT community primarily uses Python.

Writing a `coverage.py` plugin might be the best solution for this problem [per their docs](https://coverage.readthedocs.io/en/6.0/plugins.html):

> Plugins can alter a number of aspects of coverage.py’s behavior, including implementing coverage measurement for non-Python files.

I also think that this plugin should live outside `dbt-sugar` for the following reasons:
1. Avoiding the dependence on `sugar_config.yml`; code coverage should be plug-and-play.
2. Closer alignment with `coverage.py` and only including what's required to test code coverage.

Let me know what you think. 
Thanks, Kshitij

**Comment by bastienboutonnet** [comment]
Makes sense!

I wouldn't re-invent the wheel either. We actually have the ability to make this plugin independent by not putting it in core or so. Is that what you meant by outside of dbt-sugar or are you thinking you'd like to create a separate repo somewhere?

Both options work with me. Let me know how I can support you :)

Ultimately you'll most likely always be dependent on sugar config since to output test results you'll need to run dbt-sugar. Although we could allow DBT sugar to output a generic JSON artefact that the plugins would know how to parse independently of a run. That's also an option.

**Comment by k-aranke** [comment]
Looks like Slido beat me to it, closing this issue.

https://github.com/slidoapp/dbt-coverage

**Comment by bastienboutonnet** [comment]
Oh very interesting. Thanks for the tip. I'll look into the package and probably leverage it as a dependency to do that from dbt-sugar, although it's not totally needed now.
