### ISSUE TITLE
Add support for Spark/Databricks connector

### ISSUE THREAD

**Issue by jelstongreen** [bitpicky/dbt-sugar#359]
**Is your feature request related to a problem? Please describe.**
Currently unable to use dbt-sugar with out Databricks hosted solution

**Describe the solution you'd like**
Please add a connector for Spark/Databricks

**Describe alternatives you've considered**

**Additional context**
Would be happy to assist if required.

**Comment by bastienboutonnet** [comment]
Hi @jelstongreen thanks for the issue and welcome to the community.

As mentioned in discord, currently this is going to have to be entirely community-driven as I cannot do this on my own. I don't have the tech resources or knowledge.

That being said, I'm all in for helping with development, pointing you to the places in the code and coming up with some architectural decisions etc.

You say you'd be happy to help which is great. 

Maybe a first step would be to start outlining a bit what is required architecturally.

Currently dbt-sugar uses dbt-core stuff + sqlalchemy to talk to databases. If we could leverage either existing tech from dbt-spark (provided they're stable enough) or plug in our own connectors we should be able to come to the same abstractions and contracts and make the tool work.

Let me know!

**Comment by bastienboutonnet** [comment]
Hey @jelstongreen Now it's my turn to apologise for the delay.

To be completely honest, I have no idea about spark. But I think that indeed it may make sense to try and leverage the dbt internals as much as possible especially because they're moving towards a stable API. 

So I think I'd totally welcome that contribution if you had an idea about how to go about it. 

In fact someone else wants to contribute an adaptor for GCP and they're also thinking of using the dbt API itself: https://github.com/bitpicky/dbt-sugar/issues/170 and I think it makes sense. 

Let me know if I can be of any help in the process!
