### ISSUE TITLE
Support private key-based connections to Snowflake

### ISSUE THREAD

**Issue by badge** [bitpicky/dbt-sugar#409]
**Is your feature request related to a problem? Please describe.**
It is not possible to connect to a Snowflake instance where a user's authentication happens via an RSA private key, this is preventing us from using dbt-sugar.

**Describe the solution you'd like**
dbt-sugar to support RSA private keys for Snowflake connections

**Describe alternatives you've considered**
The alternative is setting up a different user login method, but this is less secure.

**Comment by bastienboutonnet** [comment]
Hey @badge thanks a lot for your interest in the tool.

Quick question, I assume dbt allows for that kind of connection in its profile right?

I've been thinking of finding some time to rework the entire package to leverage dbt's API more directly now that they have a stable version. In that case, instead of us reading the profile "manually" we could make dbt read it and then pass that to the connector.

I'll have to look into dbt's code to see a bit more.

Would it be something you may want to contribute to? I'd be more than happy to assist you with that. Otherwise, it may take a bit of time as I am a little snowed under with my main job.

Let me know!

**Comment by bastienboutonnet** [comment]
Oh! I see that you already contributed! That's super awesome. I'll take a look later today and hopefully we can get that merged so that you can continue and hopefully it works out for you.

I'm in serious need or extra pairs of hands on this project given the intention to leverage dbt's API directly so your contribution is a blessing!
